version: '2'
services:
  api:
    container_name: prescription_api
    build: .
    image: openjdk:8-jdk-alpine
    ports:
      - 8080:8080
    networks:
      - prescription
networks:
  prescription:
    driver: bridge